#!/bin/bash

set -eu; # fail fast

# Check the argument count
(( $# == 1 )) || {
   echo >&2 "usage: $0 args..."
   exit 2
}

# Read script arguments

# Store playbook code in a temp file to pass to nc later.
playbook_file=$(mktemp -t "playbook.code.XXXX")
# Store nc output in a temp file to display later.
command_out=$(mktemp -t "command.out.XXXX")
# Delete the temp files on exit.
trap "rm $playbook_file $command_out" EXIT





# Write commands set in environment to file.
echo "$RD_CONFIG_PLAYBOOK_CODE" > $playbook_file

echo "DEBUG: Executinging ansible-playbook $playbook_file"
echo "DEBUG: Code content:"
cat $playbook_file

exit $?
